name: GitHub Action PUSH - Pull Request Template types 
run-name: Running - ${{ github.event_name }}
on: 
  pull_request: 
    types:
      - opened
      - reopened
      - closed
jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps: 
      - name: Comentário
        run: |
          echo "Comentário PULL REQUEST Workflow - types"