name: GitHub Action PUSH - Pull Request Template Geral 
run-name: Running - ${{ github.event_name }}
on: 
  pull_request: 
    types:
      - opened
      - reopened
      - closed
    branches:
      - master
    paths:
      - '**.txt'
jobs: 
  on-push:
    runs-on: ubuntu-latest
    steps: 
      - name: Comentário
        run: |
          echo "Comentário PULL REQUEST Workflow - Geral"